eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
mybatis:
  config-locations: classpath:mapping/confg.xml
  mapper-locations: classpath:mapping/mapper/*.xml
  type-aliases-package: com.jk.model
server:
  port: 8081
spring:
  application:
    name: cloud-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/travel?useUnicode=true&characterEncoding=utf-8
    username: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1



