server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    name: travel-consumer
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  feign:
    hystrix:
      enabled: false
